config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from app.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/', login_view, name='login'),
    path('pessoa/', PessoaView.as_view(), name='pessoa'),
    path('buscar/', buscarView, name='buscar'),
    path('cadastraranimal/', cadastrarAnimalView, name='cadastraranimal'),
    path('deletaranimal/<int:pk>/', deletarAnimalView, name='deletaranimal'),
    path('cadastro/', cadastrar_usuario, name='cadastro'),
    path('logout/', logout_view, name='logout'),
    path('animal/<int:pk>/', detalhe_animal, name='detalheanimal'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.hashers import make_password, check_password

class Pessoa(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Nome Completo")
    data_nasc = models.DateField(verbose_name="Data de nascimento", null=True, blank=True)
    endereco = models.CharField(max_length=200, verbose_name="Endereço")
    email = models.EmailField(unique=True, verbose_name="Email")
    senha = models.CharField(max_length=128, verbose_name="Senha")
    telefone = models.CharField(max_length=15, verbose_name="Telefone")

    def set_password(self, raw_password):
        self.senha = make_password(raw_password)

    def check_password(self, raw_password):
        return check_password(raw_password, self.senha)
    
    def __str__(self):
        return f"{self.nome}, {self.data_nasc}, {self.endereco}, {self.email}, {self.senha}, {self.telefone}"

    class Meta:
        verbose_name = "Pessoa"
        verbose_name_plural = "Pessoas"


class Instituicao(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Nome da Instituição")
    cnpj = models.CharField(max_length=18, verbose_name="CNPJ")
    endereco = models.CharField(max_length=200, verbose_name="Endereço")
    email = models.EmailField(verbose_name="Email")
    senha = models.CharField(max_length=100, verbose_name="Senha")
    telefone = models.CharField(max_length=15, verbose_name="Telefone")

    def __str__(self):
        return f"{self.nome}, {self.cnpj}, {self.endereco}, {self.email}, {self.senha}, {self.telefone}"

    class Meta:
        verbose_name = "Instituição"
        verbose_name_plural = "Instituições"

class Animal(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Nome do Animal")
    especie = models.CharField(max_length=50, verbose_name="Espécie")
    genero = models.CharField(max_length=50, verbose_name="Gênero")
    cidade = models.CharField(max_length=100, verbose_name="Cidade")
    doador = models.ForeignKey(Pessoa, on_delete=models.CASCADE, verbose_name="Doador")
    descricao = models.TextField(blank=True, null=True)
    imagem = models.ImageField(upload_to='animais/', blank=True, null=True)

    def __str__(self):
        return f"{self.nome}, {self.especie}, {self.genero}, {self.cidade}, Doador: {self.doador}, {self.imagem}"

    class Meta:
        verbose_name = "Animal"
        verbose_name_plural = "Animais"

class Adocao(models.Model):
    doador = models.ForeignKey(Pessoa, on_delete=models.CASCADE, verbose_name="Doador")
    adotante = models.ForeignKey(Pessoa, related_name='adotante', on_delete=models.CASCADE, verbose_name="Adotante")
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE, verbose_name="Animal")
    data_adocao = models.DateField(auto_now_add=True, verbose_name="Data de Adoção")

    def __str__(self):
        return f"{self.doador}, {self.adotante},{self.animal}, {self.data_adocao}"

    class Meta:
        verbose_name = "Adoção"
        verbose_name_plural = "Adoções"

class Evento(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Nome do Evento")
    instituicao = models.ForeignKey(Instituicao, on_delete=models.CASCADE, verbose_name="Instituição")
    data_hora = models.DateTimeField(verbose_name="Data e Hora do Evento")
    local = models.CharField(max_length=200, verbose_name="Local do Evento")
    descricao = models.TextField(verbose_name="Descrição do Evento")

    def __str__(self):
        return f"{self.nome}, {self.instituicao}, {self.data_hora}, {self.local}, {self.descricao}"

    class Meta:
        verbose_name = "Evento"
        verbose_name_plural = "Eventos"

app/templates/animaldetalhes.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Animal</title>
</head>
<body>
    
</body>
</html>

app/templates/buscar.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8" />
    <title>Resultados da Busca</title>
</head>

<body>
    <h1>Resultados da busca por "{{ query }}"</h1>

    {% if resultados %}
    <ul>
        {% for animal in resultados %}
        <li>{{ animal.nome }}</li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Nenhum animal encontrado para "{{ query }}"</p>
    {% endif %}

    <a href="{% url 'index' %}">Voltar para a página inicial</a>
</body>

</html>

app/templates/cadastraranimal.html
{% load static %}
<!-- templates/cadastrar_animal.html -->
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>Cadastrar Animal</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <link rel="icon" href="{% static 'img/icon.ico' %}" type="image/x-icon"/>

    <style>
    body{
        background-color: #ffff;
    }

    .container{
        font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        justify-content: center;
        text-align: center;
    }

    .formulario{
        background-color: #ffefcf;
        padding: 10px;
        margin-top: 5vh;
        margin-left: 80vh;
        margin-right: 80vh;
        border: solid 1px grey;
        border-radius: 30px;
        text-align: center;
    }

    .formulario, input, select, textarea{
            text-align: center;
    }

    input[type="file"] {
        display: none;
    }

    .custom-file-upload {
        background-color: #245ac0;
        color: white;
        padding: 8px 15px;
        border-radius: 8px;
        cursor: pointer;
        transition: 0.3s;
    }

    .custom-file-upload:hover {
        background-color: #163392;
    }
    </style>
</head>
<body>
    {% include 'partials/header.html' %}

    <div class="container text-center">
        <h1>Cadastrar Animal</h1>
    </div>

    {% if messages %}
      {% for message in messages %}
        <p style="color: green">{{ message }}</p>
      {% endfor %}
    {% endif %}

    <form method="post" class="formulario" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_nome" class="form-label"><b>Nome</b></label>
            <input type="text" name="nome" id="id_nome" class="form-control" placeholder="Digite o nome do animal" required>
        </div>
    
        <div class="mb-3">
            <label for="id_especie" class="form-label"><b>Espécie</b></label>
            <input type="text" name="especie" id="id_especie" class="form-control" placeholder="Ex: cachorro, gato..." required>
        </div>
    
        <div class="mb-3">
            <label for="id_genero" class="form-label"><b>Gênero</b></label>
            <select name="genero" id="id_genero" class="form-control" required>
                <option value="">Selecione o gênero</option>
                <option value="Macho">Macho</option>
                <option value="Fêmea">Fêmea</option>
            </select>
        </div>
    
        <div class="mb-3">
            <label for="id_cidade" class="form-label"><b>Cidade</b></label>
            <input type="text" name="cidade" id="id_cidade" class="form-control" placeholder="Digite a cidade do animal" required>
        </div>
    
        <div class="mb-3">
            <label for="id_descricao" class="form-label"><b>Descrição</b></label>
            <textarea name="descricao" cols="40" rows="4" class="form-control" placeholder="Digite uma breve descrição sobre o animal..." required id="id_descricao"></textarea>
        </div>
    
        <div class="mb-3">
            <label class="form-label"><b>Imagem</b></label><br>
            <label for="id_imagem" class="custom-file-upload">
              Escolher imagem
            </label>
            <input type="file" name="imagem" id="id_imagem" accept="image/*">
          </div>
        <button type="submit" class="btn btn-success">Cadastrar</button>
    </form>
    
    <div class="mt-3 mb-4" style="margin-left: 20px;">
        <a href="{% url 'index' %}" class="btn btn-secondary px-4">Voltar</a>
    </div>

    {% include 'partials/footer.html' %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>
</html>

app/templates/detalhe_animal.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>{{ animal.nome }} - Detalhes</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <link rel="icon" href="{% static 'img/icon.ico' %}" type="image/x-icon"/>
</head>
<body>
    {% include 'partials/header.html' %}

    <div class="container mt-4 text-center">
        <h1>{{ animal.nome }}</h1>
        {% if animal.imagem %}
            <img src="{{ animal.imagem.url }}" alt="{{ animal.nome }}" class="img-fluid rounded mb-3" style="max-height: 300px;">
        {% endif %}
        <p><b>Espécie:</b> {{ animal.especie }}</p>
        <p><b>Gênero:</b> {{ animal.genero }}</p>
        <p><b>Cidade:</b> {{ animal.cidade }}</p>
        <p><b>Descrição:</b> {{ animal.descricao }}</p>

        <a href="{% url 'index' %}" class="btn btn-secondary">Voltar</a>
    </div>

    {% include 'partials/footer.html' %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>
</html>

app/templates/dieta_objetivo.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dieta Personalizada</title>
    <!-- Incluindo Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">

    <style>
        body{
            background: linear-gradient(to bottom, white, rgb(177, 173, 173));
        }

        .card{
            background-color: #1d1d1d;
            color: white;
        }

        .container{
            font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
            margin-top: 20px;
            margin-bottom: 20px;
            display: flex;
            justify-content: center;
        }

        .col{
            margin-bottom: 50px;
            margin-left: 50px;
            margin-right: 50px;
        }
    </style>
</head>
<body>
    {% include 'partials/header.html' %}

    <!-- Mensagem de boas vindas -->
    <div class="container text-center">
        <h1><b>DIETA PERSONALIZADA</b></h1>
    </div>

    <!-- Incluido os Cards -->
     
    <div class="container text-center">
        <div class="row gx-5">
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <img src="https://sdmntprwestus2.oaiusercontent.com/files/00000000-5e04-61f8-b102-f80f0551cd84/raw?se=2025-07-15T11%3A45%3A28Z&sp=r&sv=2024-08-04&sr=b&scid=bd71c3cc-aef1-58f2-a261-0587be0dfc0a&skoid=60f2aa1f-3685-43ee-be37-d8c8d08d5a64&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-07-14T22%3A09%3A15Z&ske=2025-07-15T22%3A09%3A15Z&sks=b&skv=2024-08-04&sig=E6DyiMLABFMPeCwzNlZkrobu6Cn68irP8j0VAY47/u8%3D" class="card-img-top" alt="exercicios_personalizados">
                    <div class="card-body">
                        <h5 class="card-title">Exercícios Personalizados</h5>
                        <p class="card-text">Aqui personalizamos exercícios de acordo com o seu objetivo.</p>
                        <a href="plano_atividade" class="btn btn-primary">Entrar</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <img src="https://i.pinimg.com/736x/90/b5/e6/90b5e64f381ad32c44fbb1512037c6ca.jpg" class="card-img-top" alt="dieta">
                    <div class="card-body">
                        <h5 class="card-title">Dieta Personalizada</h5>
                        <p class="card-text">Aqui personalizamos uma dieta de acordo com o seu objetivo.</p>
                        <a href="dieta_objetivo" class="btn btn-primary">Entrar</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <img src="https://i.pinimg.com/736x/3a/e0/7c/3ae07c4895bda524db1e8f4e4d6cb004.jpg" class="card-img-top" alt="dieta">
                    <div class="card-body">
                        <h5 class="card-title">Exercícios</h5>
                        <p class="card-text">Aqui possuimos um quadro com uma ampla gama de exercícios.</p>
                        <a href="exercicio" class="btn btn-primary">Entrar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'partials/footer.html' %}
    <!-- Incluindo jQuery e Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>
</html>

app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Inicial</title>
    <!-- Incluindo Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <link rel="icon" href="{% static 'img/icon.ico' %}" type="image/x-icon"/>

    <style>
        body {
            background: #ffff;
            cursor: url("{% static 'img/paw.png' %}"),
            auto;
        }

        a, button, .img-container{
            cursor: url("{% static 'img/pawclick.png' %}"), pointer;
        }

        .card {
            background-color: #e1d3be;
            color: black;
        }

        .card-img-top {
            height: 200px;
            object-fit: cover;
            cursor: pointer;
        }

        .img-container {
            height: 200px;
            display: flex;
            justify-content: center;
            align-items: center;
            overflow: hidden;
        }

        .img-container img {
            height: 100%;
            width: 100%;
            object-fit: cover;
            transition: all 0.4s ease;
        }

        .img-container:hover img {
            transform: scale(1.2);
            object-fit: contain;
            width: auto;
            height: 200px;
            transform: scale(1.2);
        }

        .container {
            font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
            margin-bottom: 20px;
            justify-content: center;
        }

        .col {
            margin-bottom: 50px;
            margin-left: 50px;
            margin-right: 50px;
        }

        p {
            display: flex;
            font-size: 20px;
            justify-content: center;
            align-items: center;
        }

        h2{
            display: flex;
            justify-content: center;
            align-items: center;
            margin-top: 30px;
        }
    </style>
</head>

<body>
    {% include 'partials/header.html' %}

    <!-- Mensagem de boas vindas -->
    {% if pessoa %}
        <h2 class="text">Olá, {{ pessoa.nome }}! 🐾</h2>
    {% endif %}
    
    <div class="container text-center">
        <h1><b>Bem vindo ao AristoPet</b></h1>
        <p>
            Aqui, cada latido e ronronar pode transformar uma vida. <br>
            Adote um pet, ganhe um amor para toda a vida. <br>
            Conheça algumas dessas fofuras que estão esperando por você!
        </p>
    </div>

    <!-- Incluido os Cards -->

    <div class="container text-center">
        <div class="row gx-5">
            {% for animal in animais %}
            <div class="col">
                <div class="card" style="width: 18rem; overflow: hidden;">

                    <div class="img-container">
                        <!-- Se você tiver imagem no modelo, usa aqui. Se não, coloca imagem padrão -->
                        {% if animal.imagem %}
                        <img src="{{ animal.imagem.url }}" class="card-img-top img-clickable" alt="{{ animal.nome }}">
                        {% else %}
                        <img src="https://via.placeholder.com/286x200.png?text=Sem+Imagem" class="card-img-top img-clickable" alt="Sem imagem disponível">
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <p class="card-text">
                            Nome: {{ animal.nome }} <br>
                            Espécie: {{ animal.especie }} <br>
                            Gênero: {{ animal.genero }} <br>
                            Cidade: {{ animal.cidade }}
                        </p>
                        <!-- Link de exemplo, ajuste se quiser -->
                        <a href="{% url 'detalheanimal' animal.pk %}" class="btn btn-success">Entrar</a>
                        <a href="{% url 'deletaranimal' animal.pk %}" class="btn btn-danger">Excluir</a>
                    </div>
                </div>
            </div>
            {% empty %}
            <p>Nenhum animal cadastrado ainda.</p>
            {% endfor %}
        </div>
    </div>
    

    {% include 'partials/footer.html' %}
    <!-- Incluindo jQuery e Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>

</html>

app/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <!-- Incluindo Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">

    <style>
        body{
            background: #ffff;
        }

        .container{
            font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
            justify-content: center;
        }

        .formulario{
            background-color: #ffefcf;
            padding: 10px;
            margin-top: 5vh;
            margin-bottom: 15vh;
            margin-left: 80vh;
            margin-right: 80vh;
            border: solid 1px grey;
            border-radius: 30px;
        }

        .formulario, input, select, textarea{
            text-align: center;
        }
    </style>
</head>
<body>
    {% include 'partials/header.html' %}

    <!-- Mensagem de boas vindas -->
    
    <div class="container text-center">
        <h1><b>Realize seu Login</b></h1>
    </div>

    {% if messages %}
    <div class="container mt-3">
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-info{% endif %}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    </div>
    {% endif %}

    <form class="formulario" method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="email" class="form-label"><b>Email</b></label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Digite seu email" required>
        </div>
        <div class="mb-3">
            <label for="senha" class="form-label"><b>Senha</b></label>
            <input type="password" class="form-control" id="senha" name="senha" placeholder="Digite sua senha" required>
        </div>
        
        <button type="submit" class="btn btn-success">Enviar</button>
    </form>

    {% include 'partials/footer.html' %}
    <!-- Incluindo jQuery e Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>
</html>

app/templates/pessoa.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>
    <!-- Incluindo Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">

    <style>
        body{
            background: #ffff;
        }

        .container{
            font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
            justify-content: center;
        }

        .formulario{
            background-color: #ffefcf;
            padding: 10px;
            margin-top: 5vh;
            margin-left: 80vh;
            margin-right: 80vh;
            border: solid 1px grey;
            border-radius: 30px;
        }

        .formulario, input, select, textarea{
            text-align: center;
        }

        .p-container{
            text-align: center;
            margin-top: 10px;
            margin-bottom: 5vh;
        }
    </style>
</head>
<body>
    {% include 'partials/header.html' %}

    <!-- Mensagem de boas vindas -->
    <div class="container text-center">
        <h1><b>Cadastre-se</b></h1>
    </div>
    <form class="formulario" method="POST" action="{% url 'cadastro' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="nome" class="form-label"><b>Nome</b></label>
            <input type="text" class="form-control" id="nome" name="nome" placeholder="Digite seu nome" required>
        </div>
        <div class="mb-3">
            <label for="data_nascimento" class="form-label"><b>Data de Nascimento</b></label>
            <input type="date" class="form-control" id="data_nascimento" name="data_nascimento" placeholder="dd/mm/aaaa" required>
          </div>
        <div class="mb-3">
            <label for="endereco" class="form-label"><b>Endereço</b></label>
            <input type="text" class="form-control" id="endereco" name="endereco" placeholder="Digite seu endereço" required>
        </div>
        <div class="mb-3">
            <label for="telefone" class="form-label"><b>Telefone</b></label>
            <input type="tel" class="form-control" id="telefone" name="telefone" placeholder="(XX) X XXXX-XXXX" pattern="\d{10,11}" maxlength="11" oninput="this.value=this.value.replace(/\D/g,'')" required>
        </div>
        <div class="mb-3">
            <label for="email" class="form-label"><b>Email</b></label>
            <input type="email" class="form-control" id="email" name="email"  placeholder="Digite seu email" required>
        </div>
        <div class="mb-3">
            <label for="senha" class="form-label"><b>Senha</b></label>
            <input type="password" class="form-control" id="senha" name="senha"  placeholder="Digite sua senha" required>
        </div>
        
        <button type="submit" class="btn btn-success">Enviar</button>
    </form>
    <div class="p-container">
        <li class="nav-item">
            Já possui uma conta?
            <a class="nav-link active" aria-current="page" href="/login/">Fazer Login</a>
        </li>
    </div>

    {% include 'partials/footer.html' %}
    <!-- Incluindo jQuery e Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>
</html>